version: '3.7'

services:
  jenkins-linux01-dev:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
      target: development
    restart: always
    environment:
      - TZ=Asia/Tokyo
      #- DISPLAY=":10.0"
    volumes:
      # sshを保存
      - ./data/jenkins/ssh:/var/lib/jenkins/.ssh
      # DockerでGUIを表示する
      - /tmp/.X11-unix:/tmp/.X11-unix # mount the X11 socket
      # 共有メモリ
      - /dev/shm:/dev/shm
      # Jenkins内で使用する共有ソフト
      - ./data/tools:/tools
      # Jenkisのデータを保存
      - ./data/jenkins/jenkins_home:/var/jenkins_home
      # rootをマウント
      - ./data/jenkins/root:/root
      # ホストのdocker.sockをマウント
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # jenkins port
      - '36001:8080'
      - '37001:50000'