version: '3.7'

services:
  jenkins-linux01-dev:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
      target: development
    restart: always
    environment:
      - TZ=Asia/Tokyo
      #- DISPLAY=":10.0"
    volumes:
      - ./data/jenkins/ssh:/var/lib/jenkins/.ssh
      #- ./data/jenkins/etc:/etc
      - /tmp/.X11-unix:/tmp/.X11-unix # mount the X11 socket
      #- /run/dbus:/run/dbus
      - /dev/shm:/dev/shm
      #- /usr:/vm/usr
      - ./data/tools:/tools
      - ./data/jenkins/jenkins_home:/var/jenkins_home
      - ./data/jenkins/root:/root
      # ホストのdocker.sockをマウント
      - /var/run/docker.sock:/var/run/docker.sock
    #devices:
    #  - /dev/dri
    ports:
      # jenkins port
      - '36001:8080'
      - '37001:50000'